version: "2"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: crawler
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 80:80
